using System.Collections;
using System.Collections.Generic;
using UnityEngine;


namespace HANA_ClipDatas
{
    public class HANA_ClipData
    {
        public static readonly Dictionary<string, string> clipNameTable_VRoid = new Dictionary<string, string>()
        {
            {"BrowDownLeft",        "browDownLeft"},
            {"BrowDownRight",       "browDownRight"},
            {"BrowInnerUp",         "browInnerUp"},
            {"BrowOuterUpLeft",     "browOuterUpLeft"},
            {"BrowOuterUpRight",    "browOuterUpRight"},
            {"CheekPuff",           "cheekPuff"},
            {"CheekSquintLeft",     "cheekSquintLeft"},
            {"CheekSquintRight",    "cheekSquintRight"},
            {"EyeBlinkLeft",        "Fcl_EYE_Close_L"},
            {"EyeBlinkRight",       "Fcl_EYE_Close_R"},
            {"EyeLookDownLeft",     "eyeLookDownLeft"},
            {"EyeLookDownRight",    "eyeLookDownRight"},
            {"EyeLookInLeft",       "eyeLookInLeft"},
            {"EyeLookInRight",      "eyeLookInRight"},
            {"EyeLookOutLeft",      "eyeLookOutLeft"},
            {"EyeLookOutRight",     "eyeLookOutRight" },
            {"EyeLookUpLeft",       "eyeLookUpLeft"},
            {"EyeLookUpRight",      "eyeLookUpRight"},
            {"EyeSquintLeft",       "eyeSquintLeft"},
            {"EyeSquintRight",      "eyeSquintRight"},
            {"EyeWideLeft",         "eyeWideLeft"},
            {"EyeWideRight",        "eyeWideRight"},
            {"JawForward",          "jawForward"},
            {"JawLeft",             "jawLeft"},
            {"JawOpen",             "jawOpen"},
            {"JawRight",            "jawRight"},
            {"MouthClose",          "mouthClose"},
            {"MouthDimpleLeft",     "mouthDimpleLeft"},
            {"MouthDimpleRight",    "mouthDimpleRight"},
            {"MouthFrownLeft",      "mouthFrownLeft"},
            {"MouthFrownRight",     "mouthFrownRight"},
            {"MouthFunnel",         "mouthFunnel"},
            {"MouthLeft",           "mouthLeft"},
            {"MouthLowerDownLeft",  "mouthLowerDownLeft"},
            {"MouthLowerDownRight", "mouthLowerDownRight"},
            {"MouthPressLeft",      "mouthPressLeft"},
            {"MouthPressRight",     "mouthPressRight"},
            {"MouthPucker",         "mouthPucker"},
            {"MouthRight",          "mouthRight"},
            {"MouthRollLower",      "mouthRollLower"},
            {"MouthRollUpper",      "mouthRollUpper"},
            {"MouthShrugLower",     "mouthShrugLower"},
            {"MouthShrugUpper",     "mouthShrugUpper"},
            {"MouthSmileLeft",      "mouthSmileLeft"},
            {"MouthSmileRight",     "mouthSmileRight"},
            {"MouthStretchLeft",    "mouthStretchLeft"},
            {"MouthStretchRight",   "mouthStretchRight"},
            {"MouthUpperUpLeft",    "mouthUpperUpLeft"},
            {"MouthUpperUpRight",   "mouthUpperUpRight"},
            {"NoseSneerLeft",       "noseSneerLeft"},
            {"NoseSneerRight",      "noseSneerRight"},
            {"TongueOut",           "tongueOut"},
        };

        public static readonly Dictionary<string, string> clipNameTable_def = new Dictionary<string, string>()
        {
            {"BrowDownLeft",        "browDownLeft"},
            {"BrowDownRight",       "browDownRight"},
            {"BrowInnerUp",         "browInnerUp"},
            {"BrowOuterUpLeft",     "browOuterUpLeft"},
            {"BrowOuterUpRight",    "browOuterUpRight"},
            {"CheekPuff",           "cheekPuff"},
            {"CheekSquintLeft",     "cheekSquintLeft"},
            {"CheekSquintRight",    "cheekSquintRight"},
            {"EyeBlinkLeft",        "eyeBlinkLeft"},
            {"EyeBlinkRight",       "eyeBlinkRight"},
            {"EyeLookDownLeft",     "eyeLookDownLeft"},
            {"EyeLookDownRight",    "eyeLookDownRight"},
            {"EyeLookInLeft",       "eyeLookInLeft"},
            {"EyeLookInRight",      "eyeLookInRight"},
            {"EyeLookOutLeft",      "eyeLookOutLeft"},
            {"EyeLookOutRight",     "eyeLookOutRight" },
            {"EyeLookUpLeft",       "eyeLookUpLeft"},
            {"EyeLookUpRight",      "eyeLookUpRight"},
            {"EyeSquintLeft",       "eyeSquintLeft"},
            {"EyeSquintRight",      "eyeSquintRight"},
            {"EyeWideLeft",         "eyeWideLeft"},
            {"EyeWideRight",        "eyeWideRight"},
            {"JawForward",          "jawForward"},
            {"JawLeft",             "jawLeft"},
            {"JawOpen",             "jawOpen"},
            {"JawRight",            "jawRight"},
            {"MouthClose",          "mouthClose"},
            {"MouthDimpleLeft",     "mouthDimpleLeft"},
            {"MouthDimpleRight",    "mouthDimpleRight"},
            {"MouthFrownLeft",      "mouthFrownLeft"},
            {"MouthFrownRight",     "mouthFrownRight"},
            {"MouthFunnel",         "mouthFunnel"},
            {"MouthLeft",           "mouthLeft"},
            {"MouthLowerDownLeft",  "mouthLowerDownLeft"},
            {"MouthLowerDownRight", "mouthLowerDownRight"},
            {"MouthPressLeft",      "mouthPressLeft"},
            {"MouthPressRight",     "mouthPressRight"},
            {"MouthPucker",         "mouthPucker"},
            {"MouthRight",          "mouthRight"},
            {"MouthRollLower",      "mouthRollLower"},
            {"MouthRollUpper",      "mouthRollUpper"},
            {"MouthShrugLower",     "mouthShrugLower"},
            {"MouthShrugUpper",     "mouthShrugUpper"},
            {"MouthSmileLeft",      "mouthSmileLeft"},
            {"MouthSmileRight",     "mouthSmileRight"},
            {"MouthStretchLeft",    "mouthStretchLeft"},
            {"MouthStretchRight",   "mouthStretchRight"},
            {"MouthUpperUpLeft",    "mouthUpperUpLeft"},
            {"MouthUpperUpRight",   "mouthUpperUpRight"},
            {"NoseSneerLeft",       "noseSneerLeft"},
            {"NoseSneerRight",      "noseSneerRight"},
            {"TongueOut",           "tongueOut"},
        };

        public static readonly Dictionary<string, float> clipWeightTable_def = new Dictionary<string, float>()
        {
            {"BrowDownLeft",        100.0f },
            {"BrowDownRight",       100.0f },
            {"BrowInnerUp",         100.0f },
            {"BrowOuterUpLeft",     100.0f },
            {"BrowOuterUpRight",    100.0f },
            {"CheekPuff",           100.0f },
            {"CheekSquintLeft",     100.0f },
            {"CheekSquintRight",    100.0f },
            {"EyeBlinkLeft",        100.0f },
            {"EyeBlinkRight",       100.0f },
            {"EyeLookDownLeft",     100.0f },
            {"EyeLookDownRight",    100.0f },
            {"EyeLookInLeft",       100.0f },
            {"EyeLookInRight",      100.0f },
            {"EyeLookOutLeft",      100.0f },
            {"EyeLookOutRight",     100.0f },
            {"EyeLookUpLeft",       100.0f },
            {"EyeLookUpRight",      100.0f },
            {"EyeSquintLeft",       100.0f },
            {"EyeSquintRight",      100.0f },
            {"EyeWideLeft",         100.0f },
            {"EyeWideRight",        100.0f },
            {"JawForward",          100.0f },
            {"JawLeft",             100.0f },
            {"JawOpen",             100.0f },
            {"JawRight",            100.0f },
            {"MouthClose",          100.0f },
            {"MouthDimpleLeft",     100.0f },
            {"MouthDimpleRight",    100.0f },
            {"MouthFrownLeft",      100.0f },
            {"MouthFrownRight",     100.0f },
            {"MouthFunnel",         100.0f },
            {"MouthLeft",           100.0f },
            {"MouthLowerDownLeft",  100.0f },
            {"MouthLowerDownRight", 100.0f },
            {"MouthPressLeft",      100.0f },
            {"MouthPressRight",     100.0f },
            {"MouthPucker",         100.0f },
            {"MouthRight",          100.0f },
            {"MouthRollLower",      100.0f },
            {"MouthRollUpper",      100.0f },
            {"MouthShrugLower",     100.0f },
            {"MouthShrugUpper",     100.0f },
            {"MouthSmileLeft",      100.0f },
            {"MouthSmileRight",     100.0f },
            {"MouthStretchLeft",    100.0f },
            {"MouthStretchRight",   100.0f },
            {"MouthUpperUpLeft",    100.0f },
            {"MouthUpperUpRight",   100.0f },
            {"NoseSneerLeft",       100.0f },
            {"NoseSneerRight",      100.0f },
            {"TongueOut",           100.0f },
        };
    }
}
